<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ClassesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('classes')->insert([
            [
                'module_id' => 'CSU08103',
                'module_name' => 'Distributed Systems',
                'session_type' => 'Lecture',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Dr. Liliani Georgette Nyamizi',
                'day_of_week' => 'Tuesday',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'room_name' => 'TH-K',
            ],
            [
                'module_id' => 'CSU08108',
                'module_name' => 'IS Research Methods',
                'session_type' => 'Tutorial',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Dr. Daniel Ntabagi Koloseni',
                'day_of_week' => 'Tuesday',
                'start_time' => '11:00',
                'end_time' => '12:00',
                'room_name' => 'LAB-4',
            ],
            [
                'module_id' => 'CSU08103',
                'module_name' => 'Distributed Systems',
                'session_type' => 'Tutorial',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Dr. Liliani Georgette Nyamizi',
                'day_of_week' => 'Tuesday',
                'start_time' => '12:00',
                'end_time' => '13:00',
                'room_name' => 'LAB-8',
            ],
            [
                'module_id' => 'CSU08105',
                'module_name' => 'Advanced Database Technologies',
                'session_type' => 'Lecture',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Dr. Dennis Michael Lupiana',
                'day_of_week' => 'Tuesday',
                'start_time' => '15:00',
                'end_time' => '17:00',
                'room_name' => '120',
            ],
            [
                'module_id' => 'CSU08105',
                'module_name' => 'Advanced Database Technologies',
                'session_type' => 'Tutorial',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Dr. Dennis Michael Lupiana',
                'day_of_week' => 'Wednesday',
                'start_time' => '11:00',
                'end_time' => '13:00',
                'room_name' => 'LAB-8',
            ],
            [
                'module_id' => 'CSU08108',
                'module_name' => 'IS Research Methods',
                'session_type' => 'Lecture',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Dr. Daniel Ntabagi Koloseni',
                'day_of_week' => 'Wednesday',
                'start_time' => '13:00',
                'end_time' => '15:00',
                'room_name' => 'TH-E',
            ],
            [
                'module_id' => 'CSU08110',
                'module_name' => 'Customer Relationship Management',
                'session_type' => 'Tutorial',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Dr. Julius Athuman Raphael',
                'day_of_week' => 'Wednesday',
                'start_time' => '16:00',
                'end_time' => '17:00',
                'room_name' => 'TH-B',
            ],
            [
                'module_id' => 'CSU08107',
                'module_name' => 'IS Strategy & Policy Formulation',
                'session_type' => 'Tutorial',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Mr. Mugaga Leonard Mugyabuso',
                'day_of_week' => 'Thursday',
                'start_time' => '08:00',
                'end_time' => '09:00',
                'room_name' => '342',
            ],
            [
                'module_id' => 'CSU08107',
                'module_name' => 'IS Strategy & Policy Formulation',
                'session_type' => 'Lecture',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Mr. Mugaga Leonard Mugyabuso',
                'day_of_week' => 'Thursday',
                'start_time' => '09:00',
                'end_time' => '11:00',
                'room_name' => '338',
            ],
            [
                'module_id' => 'CSU08111',
                'module_name' => 'Operational Research',
                'session_type' => 'Lecture',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Mr. Salvius Raphael Mgaya',
                'day_of_week' => 'Thursday',
                'start_time' => '11:00',
                'end_time' => '13:00',
                'room_name' => '113',
            ],
            [
                'module_id' => 'CSU08104',
                'module_name' => 'Advanced Software Engineering',
                'session_type' => 'Tutorial',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Mr. Wangilisasi,L',
                'day_of_week' => 'Thursday',
                'start_time' => '14:00',
                'end_time' => '15:00',
                'room_name' => '217',
            ],
            [
                'module_id' => 'CSU08104',
                'module_name' => 'Advanced Software Engineering',
                'session_type' => 'Lecture',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Mr. Wangilisasi,L',
                'day_of_week' => 'Thursday',
                'start_time' => '15:00',
                'end_time' => '17:00',
                'room_name' => '345',
            ],
            [
                'module_id' => 'CSU08111',
                'module_name' => 'Operational Research',
                'session_type' => 'Tutorial',
                'course_id' => 'BCS',
                'course_year' => '3',
                'course_group' => 'Software Engineering',
                'lecturer_name' => 'Mr. Manase,S',
                'day_of_week' => 'Friday',
                'start_time' => '15:00',
                'end_time' => '16:00',
                'room_name' => '219',
            ],
        ]);
    }
}
